"""
Launcher script for use with IDEs like PyCharm or Spyder.

This is not the entry point for the package. That entry point is generated by
setuptools when installing BioOpti with pip.

PyCharm understands virtual environments, but Spyder does not (so far as I can
see). The easiest way to get Spyder to work is to activate the virtual
environment, and then launch Spyder from the command line.
"""

if __name__ == '__main__':
    from ccc_gui import main
    main()
